### ISSUE TITLE
Donjon latest version does no longer support multi-set of settings ?

### ISSUE THREAD

**Issue by pedrocunha** [mezis/donjon#12]

**Comment by mezis** [comment]
Intriguiging. Can you provide an example failure?

**Comment by pedrocunha** [comment]
See the diff:
https://github.com/mezis/donjon/blob/v0.0.5/lib/donjon/commands/config.rb#L20-L27

And:
https://github.com/mezis/donjon/blob/master/lib/donjon/commands/config.rb#L41-L44

**Comment by mezis** [comment]
Ah, I see what you mean. `config:set` was changed for security reasons; you can use `config:mset` for the old `config:set` behaviour (and a nice warning).

This was changed months back though ;)

**Comment by pedrocunha** [comment]
Sad :panda_face:

**Comment by mezis** [comment]
Why sad? This is was a user-requested security improvement...

**Comment by pedrocunha** [comment]
Yes that's true, I take my sad panda
